Modernize the pre-commit hook a bit
- Always run unit tests.
- Always run phpstan
- Improved wait for jobs.

diff --git a/dev/git-hooks/pre-commit b/dev/git-hooks/pre-commit
--- a/dev/git-hooks/pre-commit
+++ b/dev/git-hooks/pre-commit
@@ -1,15 +1,17 @@
 #!/bin/bash
 
-#####################################################################################
+###########################################################################
 #
 # Test our code against various unit test systems and linters and prevent commit
 # if any of them fail.
 #
 # @uses Global PHP version as different projects have different requirements.
 #
-# @version 4.5.1
-#
-#####################################################################################
+# @version 6.3.1
+
+PHP_VERSION="7.4"
+
+#############################################################################
 
 GREEN="$(tput setaf 2)"
 WHITE="$(tput setaf 7)"
@@ -18,10 +20,18 @@ RED="$(tput setaf 1)"
 BLUE="$(tput setaf 6)"
 RESET_COLOR="$(tput sgr0)"
 
-PHP='php 7.4'
-PHPCS='phpcs'
-PHPUNIT='phpunit 7.4'
-PHPSTAN='phpstan'
+# Point to specific version of PHP if supported via environmental variables.
+if [[ "true" == "$PHP_MULTI_VERSION_SUPPORT" ]]; then
+    PHP="php ${PHP_VERSION}"
+    PHPCS="phpcs ${PHP_VERSION}"
+    PHPSTAN="phpstan ${PHP_VERSION}"
+    PHPUNIT="phpunit ${PHP_VERSION}"
+else
+    PHP='php'
+    PHPCS='phpcs'
+    PHPSTAN='phpstan'
+    PHPUNIT='phpunit'
+fi
 
 PROJECT=$(${PHP} -r "echo dirname(realpath('$0'), 3);")
 ## Fix windows paths
@@ -29,8 +39,7 @@ PROJECT=${PROJECT//\\//}
 
 PHP_FILES=$(git diff-index --cached --name-only --diff-filter=ACMR HEAD | grep \\.php)
 if [[ ! "$PHP_FILES" ]]; then
-	echo "${YELLOW}[pre-commit]${BLUE} No PHP Files Changed ${RESET_COLOR}"
-	exit 0
+    echo "${YELLOW}[pre-commit]${BLUE} No Lintable PHP Files Changed ${RESET_COLOR}"
 fi
 
 function exit_reset_colors() {
@@ -39,22 +48,20 @@ function exit_reset_colors() {
 }
 
 function php_unit() {
-    if [[ "$PHP_FILES" ]]; then
-        if [[ ! -f ${PROJECT}/dev/phpunit/phpunit.xml ]] && [[ ! -f ${PROJECT}/dev/phpunit/phpunit.xml.dist ]]; then
-            echo "${YELLOW}[pre-commit]${RED} ${PROJECT}/dev/phpunit/phpunit.xml or ${PROJECT}/dev/phpunit/phpunit.xml.dist not found!"
-            exit_reset_colors
-        fi
-        echo "${YELLOW}[pre-commit]${BLUE} Running PHP Unit... ${WHITE}"
-        cd "${PROJECT}/dev/phpunit" || exit
-        OUTPUT=$(${PHPUNIT})
-        if [[ $? != 0 ]]; then
-            echo
-            echo "${BLUE}PHP Unit Failed! Fix the error before commit!"
-            echo "${RED}$OUTPUT"
-            exit_reset_colors
-        fi
-        echo "${YELLOW}[pre-commit]${GREEN} PHP Unit Tests Passed!${WHITE}"
+    if [[ ! -f ${PROJECT}/dev/phpunit/phpunit.xml ]] && [[ ! -f ${PROJECT}/dev/phpunit/phpunit.xml.dist ]]; then
+        echo "${YELLOW}[pre-commit]${RED} ${PROJECT}/dev/phpunit/phpunit.xml or ${PROJECT}/dev/phpunit/phpunit.xml.dist not found!"
+        exit_reset_colors
     fi
+    echo "${YELLOW}[pre-commit]${BLUE} Running PHP Unit... ${WHITE}"
+    cd "${PROJECT}/dev/phpunit" || exit
+    OUTPUT=$(${PHPUNIT})
+    if [[ $? != 0 ]]; then
+        echo
+        echo "${BLUE}PHP Unit Failed! Fix the error before commit!"
+        echo "${RED}$OUTPUT"
+        exit_reset_colors
+    fi
+    echo "${YELLOW}[pre-commit]${GREEN} PHP Unit Tests Passed!${WHITE}"
 }
 php_unit &
 
@@ -78,7 +85,7 @@ function php_lint() {
 php_lint 'php' &
 
 function php_code_sniffer() {
-    if [[ "$PHP_FILES" != "" ]]; then
+    if [[ "$PHP_FILES" ]]; then
         if [[ ! -f ${PROJECT}/phpcs.xml ]] && [[ ! -f ${PROJECT}/phpcs.xml.dist ]]; then
             echo "${YELLOW}[pre-commit]${RED} ${PROJECT}/phpcs.xml or ${PROJECT}/phpcs.xml.dist not found!"
             exit_reset_colors
@@ -87,7 +94,7 @@ function php_code_sniffer() {
             FILES="$FILES ${PROJECT}/${FILE}"
         done
         echo "${YELLOW}[pre-commit]${BLUE} Running PHPCS... ${WHITE}"
-        OUTPUT=$(${PHPCS} --encoding=utf-8 -s -p ${FILES})
+        OUTPUT=$(${PHPCS} --encoding=utf-8 -s -p)
         if [[ $? != 0 ]]; then
             echo
             echo "${BLUE}PHPCS failed. Fix the error before commit!"
@@ -95,42 +102,43 @@ function php_code_sniffer() {
             echo
             echo "${YELLOW}For automatic fixes run"
             echo
-            echo "${WHITE}phpcbf $FILES"
+            echo "${WHITE}phpcbf${FILES}"
             echo
             exit_reset_colors
         fi
-        echo "${YELLOW}[pre-commit]${GREEN} PHPCS Passed!${WHITE}"
+        echo "${YELLOW}[pre-commit]${GREEN} PHPCS Passed!${RESET_COLOR}"
     fi
 }
 php_code_sniffer &
 
 function php_stan() {
-	if [[ "$PHP_FILES" ]]; then
-		echo "${YELLOW}[pre-commit]${BLUE} Running PHP Stan... ${WHITE}"
-		OUTPUT=$(${PHPSTAN} analyse --no-progress --memory-limit=2G)
-		if [[ $? != 0 ]]; then
-			echo
-			echo "${BLUE}PHP Stan Failed. Fix the error before commit."
-			echo "${RED}$OUTPUT"
-			exit_reset_colors
-		fi
-		echo "${YELLOW}[pre-commit]${GREEN} PHP Stan Passed!${WHITE}"
-	fi
+    if [[ ! -f ${PROJECT}/phpstan.neon ]] && [[ ! -f ${PROJECT}/phpstan.neon.dist ]]; then
+        echo "${YELLOW}[pre-commit]${RED} ${PROJECT}/phpstan.neon or ${PROJECT}/phpstan.neon.dist not found!"
+        exit_reset_colors
+    fi
+
+    echo "${YELLOW}[pre-commit]${BLUE} Running PHP Stan... ${WHITE}"
+    OUTPUT=$(${PHPSTAN} analyse --no-progress --memory-limit=2G)
+    if [[ $? != 0 ]]; then
+        echo
+        echo "${BLUE}PHP Stan Failed. Fix the error before commit."
+        echo "${RED}$OUTPUT"
+        exit_reset_colors
+    fi
+    echo "${YELLOW}[pre-commit]${GREEN} PHP Stan Passed!${RESET_COLOR}"
 }
 php_stan &
 
 # Go through each background task
 # If it sent exit code 1, it failed and the result from `wait` will be false.
 FAIL=0
-for job in $(jobs -p); do
-	wait "$job" || ((FAIL += 1))
+while [[ $(jobs -p | wc -l) -gt 0 ]]; do
+    wait -n || (( FAIL+=1 ))
 done
-
-echo "${RESET_COLOR}"
 
 # If any of the background tasks failed, we exit 1
 if [[ $FAIL -ne 0 ]]; then
-	exit 1
+    exit 1
 else
-	exit 0
+    exit 0
 fi
